import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body>
        <Header />
        <main className="w-full min-h-screen py-16 px-4 flex justify-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
